### ISSUE TITLE
wp_enqueue_style() breaks content style in child theme

### ISSUE THREAD

**Issue by jorgeoliveiraorg** [mor10/simone#30]
As per WordPress Codex - Child Themes - importing parent theme style to child theme should not be done by using `@import` anymore. Instead, a `wp_enqueue_style()` function should be created in the child theme's functions.php file. But this method breaks the formatting of the content, as can be seen in the attached images.

Using `@import` - No problem

![screenshot_import](https://cloud.githubusercontent.com/assets/9206626/4669386/d8a62378-556d-11e4-8fc3-4a7107ff22b0.PNG)

Using `wp_enqueue_style()` - Content overlaps post meta

![screenshot_wpenqueue](https://cloud.githubusercontent.com/assets/9206626/4669387/d8aadaee-556d-11e4-80d5-f1b7c79608f5.PNG)

**Comment by Esther32** [comment]
Can anybody help me with a problem I ran into?
I installed the Simone theme today and created a child theme. In it there was a line "@import url("../simone/style.css");"

I have exactly the problem as is shown in the image above: the content on my page is set to the left and floats over the section 'author' etc.

I read in the "new" Simone theme code I shoud add this code to my child theme:
/**
- For child theme authors: To disable the styles and layouts from Simone properly,
- add the following code to your child theme functions.php file:
  *
- <?php
- add_action( 'wp_enqueue_scripts', 'dequeue_parent_theme_styles', 11 );
- function dequeue_parent_theme_styles() {
-     wp_dequeue_style( 'simone-parent-style' );
-     wp_dequeue_style( 'simone-layout' );
- }
  *
  */

And so I did.
I even removed the @import line.

It did not help. As you can tell, I have little knowlegde of css.
Can somebody please help me out?
Greatly appreciated!

**Comment by giorgioriccardi** [comment]
@Esther32 the code below works for me:

``` php
/********************************************************/
//Inheriting parent styles in WordPress child themes
/********************************************************/
add_action( 'wp_enqueue_scripts', 'enqueue_child_theme_styles', PHP_INT_MAX);

function enqueue_child_theme_styles() {
    //wp_enqueue_style( 'child-style', get_stylesheet_uri(), array('parent-theme-name-style') );
    wp_enqueue_style( 'child-style', get_stylesheet_uri(), array('simone-style') );
}
//http://mor10.com/challenges-new-method-inheriting-parent-styles-wordpress-child-themes/
```

**Comment by Esther32** [comment]
Hoi Giorgio, thanks for your reply. :)
Does it matter where I place it in the code of my child theme?
And does it need any code before or after?

Because I just tried your code and it didn't help...
I did erase the @import line already.

**Comment by giorgioriccardi** [comment]
@Esther32 
Hold on! I assumed you removed the @import url("../simone/style.css"); from your style.css
The function above goes in your functions.php file within the child-theme folder!
and yes, it matters where you paste your code. Please follow:
[https://codex.wordpress.org/Child_Themes](https://codex.wordpress.org/Child_Themes)

**Comment by Esther32** [comment]
Okay. I'm busy digesting the information in your link. And I'm not native English also, so I'm trying to cope with two languages at the time. ;)
First of all I put the functions code IN my style file, but that was a mistake.
So I have two files in my child theme folder; style and functions.

Now I'm going to read your link in detail...

**Comment by Esther32** [comment]
Okay, I read it and I tried several codes in my functions.php file. It didn't work.
I also tried yours of course.

I'm reading here, that the functions.php is not necessary anymore? Or am I confusing two different problems? _"Basically any child theme of Simone now automatically inherits the parent theme stylesheets in the right order. All you have to do is create your style.css file in the child theme and it automatically kicks in." [https://wordpress.org/support/topic/child-theme-and-enqueue-ing-new-scripts-and-styles?replies=10](url)

Back to basics: when I change my theme back to Simone, everything is fine.
When I change is to Simone-child, then I have the problem as is shown at the beginning of this topic.
So either I've been messing with the code in my child theme, or there is something wrong in the 'communication' between my child theme and its parent...

Can you advise me any further?

**Comment by Esther32** [comment]
Also: in the code you posted: should I change anything in there?
I see 'parent-theme-name' > should I not change that to 'simone'. As I said, I know little of css and php...

**Comment by giorgioriccardi** [comment]
@Esther32 please open a ticket on the forum, github is not the right place for this conversation.
Let's continue here please:
[https://wordpress.org/support/theme/simone](https://wordpress.org/support/theme/simone)

**Comment by Esther32** [comment]
Will do, thanks so far!
