### ISSUE TITLE
Small request

### ISSUE THREAD

**Issue by Lord-Kamina** [mor10/simone#46]
I was wondering if it'd be possible in future versions to wrap the responsive thumbnail functions in 
`if ( ! function_exists( ) )` as to enable people to mess around with handling of sizes (or adding extra sizes) without having to do major surgery on the parent theme files.

**Comment by mor10** [comment]
Absolutely. I will do this presently. It'll be built into the next release. In the meantime you'll be able to find it in the Development and Sassy Simone branches.

**Comment by mor10** [comment]
@Lord-Kamina Check and see if that's what you meant.
