### ISSUE TITLE
CSS Style Editor

### ISSUE THREAD

**Issue by teracomp** [mor10/simone#47]
In your CSS Style Editor (themes.php?page=editcss), the code 
line numbers overlap the textarea. This means I can't see the left margin. I'll eventually find the style (.CodeMirror-gutter .CodeMirror-linenumbers) location and fix it, but I thought I'd let you know.  

Two screenshots here: 1) default and 2) using Inspect Element to turn on the background

Default:
![simone2-cssedit-default](https://cloud.githubusercontent.com/assets/4229488/5876543/f6db75bc-a2e5-11e4-8bea-7254350ce1f8.jpg)

Background Off:
![simone2-cssedit-bg-disabled](https://cloud.githubusercontent.com/assets/4229488/5876542/f6d99882-a2e5-11e4-8554-f65834ce5349.jpg)

Keep up the great work!

**Comment by giorgioriccardi** [comment]
Hi teracomp,
I think it is a jetpack issue, the CSS Stylesheet Editor is not a Simone built-in functionality.
http://jetpack.me/support/custom-css/

**Comment by teracomp** [comment]
Ah...ok...you are correct in assuming I have installed jetpack. I'll look there for a resolution. Thanks for the super fast response!
