### ISSUE TITLE
Why Masonry?

### ISSUE THREAD

**Issue by fciotola** [mor10/simone#50]
Hi Morten why you include Masonry? i don't see grid layout in your theme, how you can use the masonry js? thanks in advance

**Comment by giorgioriccardi** [comment]
Hi fciotola,
read this post here:
http://mor10.com/free-responsive-wordpress-theme-anaximander-now-available-through-lynda-com/
the first 2 comments should give you a general direction.
Even though the theme is different, the developer is still Morten and the concept still applies.
Hope it helps

**Comment by mor10** [comment]
@fciotola Masonry is added to manage the widgets in the footer. When the windows is wide enough Masonry is triggered and organizes the footer widgets so they appear properly on all screen sizes.
